// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIfmAtc32SGhj6oeNT8Lo4jj8FiavR1eo',
    appId: '1:600665835506:web:274230227358a16f54cd6b',
    messagingSenderId: '600665835506',
    projectId: 'spotify-clone-77d3f',
    authDomain: 'spotify-clone-77d3f.firebaseapp.com',
    storageBucket: 'spotify-clone-77d3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-uOkbbm6iPos4HXN9BETIJzVQs5iShbg',
    appId: '1:600665835506:android:0fe1c91d9375e80354cd6b',
    messagingSenderId: '600665835506',
    projectId: 'spotify-clone-77d3f',
    storageBucket: 'spotify-clone-77d3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYUeEcM3XUnN48XM_Yukmpc5MeYaHZgAU',
    appId: '1:600665835506:ios:e2dfb9083eacef8f54cd6b',
    messagingSenderId: '600665835506',
    projectId: 'spotify-clone-77d3f',
    storageBucket: 'spotify-clone-77d3f.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );
}
